Pin puppet-lint to 2.3.0
Without this patch puppet-lint 2.3.1 results in this error in Ruby 1.8.7:

    SyntaxError: /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint/configuration.rb:53: undefined (?...) sequence: /^(?<option>\w+)=?$/
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint.rb:7:in `gem_original_require'
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint.rb:7:in `require'
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint.rb:7
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint/tasks/puppet-lint.rb:1:in `gem_original_require'
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint/tasks/puppet-lint.rb:1:in `require'
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppet-lint-2.3.1/lib/puppet-lint/tasks/puppet-lint.rb:1
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppetlabs_spec_helper-2.0.2/lib/puppetlabs_spec_helper/rake_tasks.rb:438:in `gem_original_require'
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppetlabs_spec_helper-2.0.2/lib/puppetlabs_spec_helper/rake_tasks.rb:438:in `require'
    /home/travis/.rvm/gems/ruby-1.8.7-p371/gems/puppetlabs_spec_helper-2.0.2/lib/puppetlabs_spec_helper/rake_tasks.rb:438
    /home/travis/build/nytm/puppet-module-confluence/Rakefile:1:in `gem_original_require'
    /home/travis/build/nytm/puppet-module-confluence/Rakefile:1:in `require'
    /home/travis/build/nytm/puppet-module-confluence/Rakefile:1
    /home/travis/.rvm/gems/ruby-1.8.7-p371/bin/ruby_executable_hooks:15
    (See full trace by running task with --trace)

The issue has been filed upstream as https://github.com/rodjek/puppet-lint/issues/759